# Generated by Django 4.1.3 on 2023-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_remove_shortenedurl_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
