# Generated by Django 4.1.3 on 2023-10-26 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_alter_shortenedurl_original_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
