# Generated by Django 4.1.3 on 2023-10-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_shortenedurl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
