# Generated by Django 4.1.3 on 2023-10-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0005_alter_shortenedurl_date_alter_shortenedurl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='date',
        ),
    ]
